# 태양광 발전량 예측 모델

- 2020년 1월 31일, 2020년 3월 31일, 2020년 5월 31일을 예측


- 하루동안의 데이터는 96개의 데이터가 생성


- 데이터는 15분 당 한개씩 생성


- 데이터 구조
    - 00:00:00 ~ 05:00:00 이 기간은 value=0 (20개) 
    - 05:15:00 ~ 20:15:00 이 기간은 value=? (63개)
    - 20:30:00 ~ 23:45:00 이 기간은 value=0 (13개)
    
- 총 63개의 각 시간을 맞추는 데이터를 분리하고 모델 생성

- 총 용량 133kw

### 1. 라이브러리 및 환경 세팅

In [1]:
import pandas as pd

### 2. 데이터 불러오기

In [2]:
data = pd.read_csv("./SolarPV_Elec_Problem.csv", header=None, names=["Date", "Value"])

In [3]:
data.head()

Date  Value
0  2019-07-01T00:00:00+09:00    0.0
1  2019-07-01T00:15:00+09:00    0.0
2  2019-07-01T00:30:00+09:00    0.0
3  2019-07-01T00:45:00+09:00    0.0
4  2019-07-01T01:00:00+09:00    0.0

### 3. 데이터 쪼개기

In [4]:
def PSH_FUNCTION_1 (data, dataframe_new, time) : 
    
    for idx in data.index : 
    
        if time in str(data.loc[idx]["Date"]) : 

            sample = pd.Series({"Date" : data.loc[idx]["Date"], "Value" : data.loc[idx]["Value"]})

            dataframe_new = dataframe_new.append(sample, ignore_index=True)
            
    dataframe_new["past_01"] = dataframe_new["Value"].shift(1)
    dataframe_new["past_02"] = dataframe_new["Value"].shift(2)
    dataframe_new["past_03"] = dataframe_new["Value"].shift(3)
    dataframe_new["past_04"] = dataframe_new["Value"].shift(4)
    dataframe_new["past_05"] = dataframe_new["Value"].shift(5)
    dataframe_new["past_06"] = dataframe_new["Value"].shift(6)
    dataframe_new["past_07"] = dataframe_new["Value"].shift(7)

    dataframe_new = dataframe_new.dropna(subset=["past_01", "past_02", "past_03", "past_04", "past_05", "past_06", "past_07"])
    
    dataframe_new = dataframe_new.reset_index()
    
    dataframe_new = dataframe_new[dataframe_new.columns[1:]]
    
    return dataframe_new

In [5]:
def PSH_FUNCTION_2 (dataframe, time) : 
    
    train = pd.DataFrame()
    test = pd.DataFrame()
    
    for idx in dataframe.index : 
        
        if dataframe.loc[idx]["Date"] == "2020-01-31T" + time + "+09:00" : 
            test = test.append(dataframe.loc[idx])
        elif dataframe.loc[idx]["Date"] == "2020-03-31T" + time + "+09:00" : 
            test = test.append(dataframe.loc[idx])
        elif dataframe.loc[idx]["Date"] == "2020-05-31T" + time + "+09:00" : 
            test = test.append(dataframe.loc[idx])
        else :
            train = train.append(dataframe.loc[idx])
            
    train = train.reset_index()
    test = test.reset_index()
    
    train = train[train.columns[1:]]
    test = test[test.columns[1:]]

    return train, test

In [6]:
data_1430 = pd.DataFrame()
data_1430 = PSH_FUNCTION_1(data = data, dataframe_new = data_1430, time = "14:30:00")
data_1430_train = PSH_FUNCTION_2(data_1430, time="14:30:00")[0]
data_1430_test = PSH_FUNCTION_2(data_1430, time="14:30:00")[1]

In [7]:
data_1430_train

Date      Value    past_01    past_02    past_03  \
0    2019-07-08T14:30:00+09:00  11.554412  20.452102  19.625412  16.201412   
1    2019-07-09T14:30:00+09:00   9.748412  11.554412  20.452102  19.625412   
2    2019-07-10T14:30:00+09:00   4.389412   9.748412  11.554412  20.452102   
3    2019-07-11T14:30:00+09:00   5.415412   4.389412   9.748412  11.554412   
4    2019-07-12T14:30:00+09:00  14.116412   5.415412   4.389412   9.748412   
5    2019-07-13T14:30:00+09:00   6.672412  14.116412   5.415412   4.389412   
6    2019-07-14T14:30:00+09:00  13.934412   6.672412  14.116412   5.415412   
7    2019-07-15T14:30:00+09:00   3.775412  13.934412   6.672412  14.116412   
8    2019-07-16T14:30:00+09:00  14.797412   3.775412  13.934412   6.672412   
9    2019-07-17T14:30:00+09:00   9.446412  14.797412   3.775412  13.934412   
10   2019-07-18T14:30:00+09:00  17.307412   9.446412  14.797412   3.775412   
11   2019-07-19T14:30:00+09:00  11.318412  17.307412   9.446412  14.797412   
12   2019-07-20T14:30:00+09:00  15.096412  11.318412  17.307412   9.446412   
13   2019-07-21T14:30:00+09:00   6.542412  15.096412  11.318412  17.307412   
14   2019-07-22T14:30:00+09:00  17.630412   6.542412  15.096412  11.318412   
15   2019-07-23T14:30:00+09:00  16.792412  17.630412   6.542412  15.096412   
16   2019-07-24T14:30:00+09:00   4.630412  16.792412  17.630412   6.542412   
17   2019-07-25T14:30:00+09:00   1.155412   4.630412  16.792412  17.630412   
18   2019-07-26T14:30:00+09:00   2.286412   1.155412   4.630412  16.792412   
19   2019-07-27T14:30:00+09:00   8.723412   2.286412   1.155412   4.630412   
20   2019-07-28T14:30:00+09:00   3.237412   8.723412   2.286412   1.155412   
21   2019-07-29T14:30:00+09:00  17.264083   3.237412   8.723412   2.286412   
22   2019-07-30T14:30:00+09:00  16.724412  17.264083   3.237412   8.723412   
23   2019-07-31T14:30:00+09:00  15.042412  16.724412  17.264083   3.237412   
24   2019-08-01T14:30:00+09:00  12.688457  15.042412  16.724412  17.264083   
25   2019-08-02T14:30:00+09:00  19.363807  12.688457  15.042412  16.724412   
26   2019-08-03T14:30:00+09:00  10.602807  19.363807  12.688457  15.042412   
27   2019-08-04T14:30:00+09:00  13.439807  10.602807  19.363807  12.688457   
28   2019-08-05T14:30:00+09:00  15.749807  13.439807  10.602807  19.363807   
29   2019-08-06T14:30:00+09:00  13.442807  15.749807  13.439807  10.602807   
..                         ...        ...        ...        ...        ...   
305  2020-05-24T14:30:00+09:00  18.556454  22.073000  11.656000  21.985000   
306  2020-05-25T14:30:00+09:00  14.647000  18.556454  22.073000  11.656000   
307  2020-05-26T14:30:00+09:00  20.710000  14.647000  18.556454  22.073000   
308  2020-05-27T14:30:00+09:00  21.331000  20.710000  14.647000  18.556454   
309  2020-05-28T14:30:00+09:00  15.469000  21.331000  20.710000  14.647000   
310  2020-05-29T14:30:00+09:00  20.327000  15.469000  21.331000  20.710000   
311  2020-05-30T14:30:00+09:00  18.676000  20.327000  15.469000  21.331000   
312  2020-06-08T14:30:00+09:00  18.138000  19.204000  18.947000  16.281000   
313  2020-06-09T14:30:00+09:00  18.200000  18.138000  19.204000  18.947000   
314  2020-06-10T14:30:00+09:00  16.992187  18.200000  18.138000  19.204000   
315  2020-06-11T14:30:00+09:00  18.288000  16.992187  18.200000  18.138000   
316  2020-06-12T14:30:00+09:00   6.096000  18.288000  16.992187  18.200000   
317  2020-06-13T14:30:00+09:00  19.762000   6.096000  18.288000  16.992187   
318  2020-06-14T14:30:00+09:00  19.422317  19.762000   6.096000  18.288000   
319  2020-06-15T14:30:00+09:00  18.216000  19.422317  19.762000   6.096000   
320  2020-06-16T14:30:00+09:00  17.483000  18.216000  19.422317  19.762000   
321  2020-06-17T14:30:00+09:00  14.785000  17.483000  18.216000  19.422317   
322  2020-06-18T14:30:00+09:00   8.594000  14.785000  17.483000  18.216000   
323  2020-06-19T14:30:00+09:00  18.806000   8.594000  14.785000  17.483000   
324  2020-06-20T14:30:00+09:00  15.329000  18.80

In [8]:
data_1430_test

Date  Value    past_01  past_02  past_03  past_04  \
0  2020-01-31T14:30:00+09:00    NaN   7.915773   11.440    6.927    1.629   
1  2020-03-31T14:30:00+09:00    NaN  22.527000   23.530   20.846   19.045   
2  2020-05-31T14:30:00+09:00    NaN  18.676000   20.327   15.469   21.331   

   past_05  past_06    past_07  
0    8.876    7.130  15.627000  
1    2.493   21.279  21.079000  
2   20.710   14.647  18.556454

### Train Valid Split & Linear Regression

In [9]:
X = data_1430_train[data_1430_train.columns[2:]]
y = data_1430_train["Value"]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.30, random_state=1234)

In [11]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [12]:
reg.score(X_train, y_train)

0.15524530688090077

In [13]:
reg.score(X_valid, y_valid)

-0.050348978349729956

In [14]:
X_test = data_1430_test[data_1430_test.columns[2:]]
y_test = data_1430_test["Value"]

In [15]:
reg.predict(X_test).round(4)

array([ 9.8591, 18.5506, 15.7664])

### LSTM 모델 구성

#### 2시 30분

In [43]:
X_train = data_1430_train[data_1430_train.columns[2:]].values
X_test = data_1430_test[data_1430_test.columns[2:]].values

y_train = data_1430_train["Value"].values
y_test = data_1430_test["Value"].values

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(335, 7)
(3, 7)
(335,)
(3,)


In [44]:
# 최종 트레이닝 셋
X_train_t = X_train.reshape(X_train.shape[0],7,1)
X_test_t = X_test.reshape(X_test.shape[0],7,1)

print("최종 Data")
print(X_train_t.shape)
print(X_test_t)
print(X_test_t.shape)
print(y_train.shape)
print(y_test.shape)

최종 Data
(335, 7, 1)
[[[ 7.915773]
  [11.44    ]
  [ 6.927   ]
  [ 1.629   ]
  [ 8.876   ]
  [ 7.13    ]
  [15.627   ]]

 [[22.527   ]
  [23.53    ]
  [20.846   ]
  [19.045   ]
  [ 2.493   ]
  [21.279   ]
  [21.079   ]]

 [[18.676   ]
  [20.327   ]
  [15.469   ]
  [21.331   ]
  [20.71    ]
  [14.647   ]
  [18.556454]]]
(3, 7, 1)
(335,)
(3,)


In [18]:
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K
from keras.callbacks import EarlyStopping

K.clear_session()
model = Sequential()
model.add(LSTM(20,input_shape = (7,1)))
model.add(Dense(1))
model.compile(loss = 'mean_squared_error', optimizer = 'adam')
model.summary()

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20)                1760      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(X_train_t,y_train, epochs = 100,
         batch_size = 16,verbose = 1)


Epoch 1/100
335/335 [==============================] - 2s 5ms/step - loss: 191.5257
Epoch 2/100
335/335 [==============================] - 0s 815us/step - loss: 169.7446
Epoch 3/100
335/335 [==============================] - 0s 886us/step - loss: 150.0499
Epoch 4/100
335/335 [==============================] - 0s 945us/step - loss: 131.1781
Epoch 5/100
335/335 [==============================] - 0s 887us/step - loss: 111.3154
Epoch 6/100
335/335 [==============================] - 0s 991us/step - loss: 91.6359
Epoch 7/100
335/335 [==============================] - 0s 856us/step - loss: 78.4702
Epoch 8/100
335/335 [==============================] - 0s 862us/step - loss: 70.8120
Epoch 9/100
335/335 [==============================] - 0s 828us/step - loss: 65.0992
Epoch 10/100
335/335 [==============================] - 0s 914us/step - loss: 59.5823
Epoch 11/100
335/335 [==============================] - 0s 827us/step - loss: 54.7695
Epoch 12/100
335/335 [==============================] - 0s 

335/335 [==============================] - 0s 768us/step - loss: 36.2011
Epoch 95/100
335/335 [==============================] - 0s 746us/step - loss: 36.2519
Epoch 96/100
335/335 [==============================] - 0s 839us/step - loss: 36.0372
Epoch 97/100
335/335 [==============================] - 0s 746us/step - loss: 35.8101
Epoch 98/100
335/335 [==============================] - 0s 771us/step - loss: 35.7728
Epoch 99/100
335/335 [==============================] - 0s 816us/step - loss: 35.7268
Epoch 100/100
335/335 [==============================] - 0s 788us/step - loss: 35.5662


In [45]:
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K
from keras.callbacks import EarlyStopping

K.clear_session()
model = Sequential()
model.add(LSTM(20,input_shape = (7,1)))
model.add(Dense(1))
model.compile(loss = 'mean_absolute_error', optimizer = 'adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20)                1760      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.fit(X_train_t,y_train, epochs = 100,
         batch_size = 16,verbose = 1)

Epoch 1/100
335/335 [==============================] - 1s 2ms/step - loss: 12.2896
Epoch 2/100
335/335 [==============================] - 0s 859us/step - loss: 11.8380
Epoch 3/100
335/335 [==============================] - 0s 835us/step - loss: 11.3351
Epoch 4/100
335/335 [==============================] - 0s 835us/step - loss: 10.8102
Epoch 5/100
335/335 [==============================] - 0s 835us/step - loss: 10.1937
Epoch 6/100
335/335 [==============================] - 0s 978us/step - loss: 9.4340
Epoch 7/100
335/335 [==============================] - 0s 811us/step - loss: 8.6519
Epoch 8/100
335/335 [==============================] - 0s 859us/step - loss: 8.0265
Epoch 9/100
335/335 [==============================] - 0s 835us/step - loss: 7.5396
Epoch 10/100
335/335 [==============================] - 0s 835us/step - loss: 7.2030
Epoch 11/100
335/335 [==============================] - 0s 835us/step - loss: 6.9283
Epoch 12/100
335/335 [==============================] - 0s 835us/step -

335/335 [==============================] - 0s 835us/step - loss: 4.7756
Epoch 98/100
335/335 [==============================] - 0s 859us/step - loss: 4.7520
Epoch 99/100
335/335 [==============================] - 0s 883us/step - loss: 4.7375
Epoch 100/100
335/335 [==============================] - 0s 811us/step - loss: 4.7333


In [62]:
y_pred = model.predict(X_test_t)
print(y_pred)

[[10.332613]
 [16.281836]
 [15.78509 ]]


### 0515

In [52]:
data_0515 = pd.DataFrame()
data_0515 = PSH_FUNCTION_1(data = data, dataframe_new = data_0515, time = "05:15:00")
data_0515_train = PSH_FUNCTION_2(data_0515, time="05:15:00")[0]
data_0515_test = PSH_FUNCTION_2(data_0515, time="05:15:00")[1]

In [22]:
X_train = data_0515_train[data_0515_train.columns[2:]].values
X_test = data_0515_test[data_0515_test.columns[2:]].values

y_train = data_0515_train["Value"].values
y_test = data_0515_test["Value"].values

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(335, 7)
(3, 7)
(335,)
(3,)


In [23]:
# 최종 트레이닝 셋
X_train_t = X_train.reshape(X_train.shape[0],7,1)
X_test_t = X_test.reshape(X_test.shape[0],7,1)

print("최종 Data")
print(X_train_t.shape)
print(X_test_t.shape)
print(y_train.shape)
print(y_test.shape)

최종 Data
(335, 7, 1)
(3, 7, 1)
(335,)
(3,)


In [48]:
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K
from keras.callbacks import EarlyStopping

K.clear_session()
model = Sequential()
model.add(LSTM(20,input_shape = (7,1)))
model.add(Dense(1))
model.compile(loss = 'mean_squared_error', optimizer = 'adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20)                1760      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [49]:
model.fit(X_train_t,y_train, epochs = 100,
         batch_size = 16,verbose = 1)

Epoch 1/100
335/335 [==============================] - 1s 2ms/step - loss: 206.0261
Epoch 2/100
335/335 [==============================] - 0s 883us/step - loss: 183.6798
Epoch 3/100
335/335 [==============================] - 0s 907us/step - loss: 161.8105
Epoch 4/100
335/335 [==============================] - 0s 835us/step - loss: 143.0247
Epoch 5/100
335/335 [==============================] - 0s 835us/step - loss: 126.2641
Epoch 6/100
335/335 [==============================] - 0s 835us/step - loss: 112.8331
Epoch 7/100
335/335 [==============================] - 0s 859us/step - loss: 101.7317
Epoch 8/100
335/335 [==============================] - 0s 835us/step - loss: 90.4426
Epoch 9/100
335/335 [==============================] - 0s 1ms/step - loss: 78.2266
Epoch 10/100
335/335 [==============================] - 0s 859us/step - loss: 68.2103
Epoch 11/100
335/335 [==============================] - 0s 811us/step - loss: 61.6606
Epoch 12/100
335/335 [==============================] - 0s 8

335/335 [==============================] - 0s 883us/step - loss: 35.6078
Epoch 97/100
335/335 [==============================] - 0s 907us/step - loss: 35.6517
Epoch 98/100
335/335 [==============================] - 0s 883us/step - loss: 35.4424
Epoch 99/100
335/335 [==============================] - 0s 979us/step - loss: 35.6743
Epoch 100/100
335/335 [==============================] - 0s 1ms/step - loss: 35.3756


In [50]:
y_pred = model.predict(X_test_t).round(4)
print(y_pred)

[[10.3326]
 [16.2818]
 [15.7851]]


### 0530

In [51]:
data_0530 = pd.DataFrame()
data_0530 = PSH_FUNCTION_1(data = data, dataframe_new = data_0530, time = "05:30:00")
data_0530_train = PSH_FUNCTION_2(data_0530, time="05:30:00")[0]
data_0530_test = PSH_FUNCTION_2(data_0530, time="05:30:00")[1]

In [28]:
X_train = data_0515_train[data_0530_train.columns[2:]].values
X_test = data_0515_test[data_0530_test.columns[2:]].values

y_train = data_0530_train["Value"].values
y_test = data_0530_test["Value"].values

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(335, 7)
(3, 7)
(335,)
(3,)


In [29]:
# 최종 트레이닝 셋
X_train_t = X_train.reshape(X_train.shape[0],7,1)
X_test_t = X_test.reshape(X_test.shape[0],7,1)

print("최종 Data")
print(X_train_t.shape)
print(X_test_t.shape)
print(y_train.shape)
print(y_test.shape)

최종 Data
(335, 7, 1)
(3, 7, 1)
(335,)
(3,)


In [30]:
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K
from keras.callbacks import EarlyStopping

K.clear_session()
model = Sequential()
model.add(LSTM(20,input_shape = (7,1)))
model.add(Dense(1))
model.compile(loss = 'mean_squared_error', optimizer = 'adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20)                1760      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.fit(X_train_t,y_train, epochs = 100,
         batch_size = 16,verbose = 1)

Epoch 1/100
335/335 [==============================] - 0s 1ms/step - loss: 2.7722e-04
Epoch 2/100
335/335 [==============================] - 0s 936us/step - loss: 2.6889e-04
Epoch 3/100
335/335 [==============================] - 0s 751us/step - loss: 2.6104e-04
Epoch 4/100
335/335 [==============================] - 0s 742us/step - loss: 2.6120e-04
Epoch 5/100
335/335 [==============================] - 0s 788us/step - loss: 2.6082e-04
Epoch 6/100
335/335 [==============================] - 0s 723us/step - loss: 2.5711e-04
Epoch 7/100
335/335 [==============================] - 0s 746us/step - loss: 2.6771e-04
Epoch 8/100
335/335 [==============================] - 0s 769us/step - loss: 2.5430e-04
Epoch 9/100
335/335 [==============================] - 0s 752us/step - loss: 2.5919e-04
Epoch 10/100
335/335 [==============================] - 0s 760us/step - loss: 2.7831e-04
Epoch 11/100
335/335 [==============================] - 0s 744us/step - loss: 2.5592e-04
Epoch 12/100
335/335 [==========

335/335 [==============================] - 0s 746us/step - loss: 1.8821e-04
Epoch 94/100
335/335 [==============================] - 0s 746us/step - loss: 1.9455e-04
Epoch 95/100
335/335 [==============================] - 0s 733us/step - loss: 2.0510e-04
Epoch 96/100
335/335 [==============================] - 0s 746us/step - loss: 1.9644e-04
Epoch 97/100
335/335 [==============================] - 0s 857us/step - loss: 1.8886e-04
Epoch 98/100
335/335 [==============================] - 0s 931us/step - loss: 1.9295e-04
Epoch 99/100
335/335 [==============================] - 0s 909us/step - loss: 1.8860e-04
Epoch 100/100
335/335 [==============================] - 0s 946us/step - loss: 1.9216e-04


In [32]:
y_pred = model.predict(X_test_t).round(4)
print(y_pred)

[[0.0008]
 [0.0008]
 [0.0423]]
